
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Achievement : Luban.BeanBase
{
    public Achievement(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["EventName"].IsString) { throw new SerializationException(); }  EventName = _buf["EventName"]; }
        { if(!_buf["MaxValue"].IsNumber) { throw new SerializationException(); }  MaxValue = _buf["MaxValue"]; }
        { if(!_buf["NameKey"].IsString) { throw new SerializationException(); }  NameKey = _buf["NameKey"]; }
        { if(!_buf["DescriptionKey"].IsString) { throw new SerializationException(); }  DescriptionKey = _buf["DescriptionKey"]; }
        { if(!_buf["AwardDiamond"].IsNumber) { throw new SerializationException(); }  AwardDiamond = _buf["AwardDiamond"]; }
    }

    public static Achievement DeserializeAchievement(JSONNode _buf)
    {
        return new Achievement(_buf);
    }

    public readonly int Id;
    public readonly string EventName;
    public readonly int MaxValue;
    public readonly string NameKey;
    public readonly string DescriptionKey;
    public readonly int AwardDiamond;
   
    public const int __ID__ = -879479025;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EventName:" + EventName + ","
        + "MaxValue:" + MaxValue + ","
        + "NameKey:" + NameKey + ","
        + "DescriptionKey:" + DescriptionKey + ","
        + "AwardDiamond:" + AwardDiamond + ","
        + "}";
    }
}

}
