
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["EntityId"].IsNumber) { throw new SerializationException(); }  EntityId = _buf["EntityId"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["MoveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["MoveSpeed"]; }
        { if(!_buf["ActiveTime"].IsNumber) { throw new SerializationException(); }  ActiveTime = _buf["ActiveTime"]; }
        { if(!_buf["BehaviourKey"].IsString) { throw new SerializationException(); }  BehaviourKey = _buf["BehaviourKey"]; }
    }

    public static Bullet DeserializeBullet(JSONNode _buf)
    {
        return new Bullet(_buf);
    }

    /// <summary>
    /// 子弹编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体编号
    /// </summary>
    public readonly int EntityId;
    public readonly float Damage;
    public readonly float MoveSpeed;
    public readonly float ActiveTime;
    public readonly string BehaviourKey;
   
    public const int __ID__ = 2000900386;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "Damage:" + Damage + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "ActiveTime:" + ActiveTime + ","
        + "BehaviourKey:" + BehaviourKey + ","
        + "}";
    }
}

}
