
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EntityGroup : Luban.BeanBase
{
    public EntityGroup(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["GroupName"].IsString) { throw new SerializationException(); }  GroupName = _buf["GroupName"]; }
        { if(!_buf["InstanceAutoReleaseInterval"].IsNumber) { throw new SerializationException(); }  InstanceAutoReleaseInterval = _buf["InstanceAutoReleaseInterval"]; }
        { if(!_buf["InstanceCapacity"].IsNumber) { throw new SerializationException(); }  InstanceCapacity = _buf["InstanceCapacity"]; }
        { if(!_buf["InstanceExpireTime"].IsNumber) { throw new SerializationException(); }  InstanceExpireTime = _buf["InstanceExpireTime"]; }
        { if(!_buf["InstancePriority"].IsNumber) { throw new SerializationException(); }  InstancePriority = _buf["InstancePriority"]; }
    }

    public static EntityGroup DeserializeEntityGroup(JSONNode _buf)
    {
        return new EntityGroup(_buf);
    }

    /// <summary>
    /// 配置编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 组名字
    /// </summary>
    public readonly string GroupName;
    /// <summary>
    /// 自动释放可释放对象的间隔秒数
    /// </summary>
    public readonly float InstanceAutoReleaseInterval;
    /// <summary>
    /// 实例对象池的容量
    /// </summary>
    public readonly int InstanceCapacity;
    /// <summary>
    /// 对象池对象过期秒数
    /// </summary>
    public readonly float InstanceExpireTime;
    /// <summary>
    /// 实体组实例对象池的优先级
    /// </summary>
    public readonly int InstancePriority;
   
    public const int __ID__ = -1367621572;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "GroupName:" + GroupName + ","
        + "InstanceAutoReleaseInterval:" + InstanceAutoReleaseInterval + ","
        + "InstanceCapacity:" + InstanceCapacity + ","
        + "InstanceExpireTime:" + InstanceExpireTime + ","
        + "InstancePriority:" + InstancePriority + ","
        + "}";
    }
}

}
