
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Equipment : Luban.BeanBase
{
    public Equipment(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["EquipmentType"].IsNumber) { throw new SerializationException(); }  EquipmentType = (EquipmentType)_buf["EquipmentType"].AsInt; }
        { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = (equipment.QualityType)_buf["Quality"].AsInt; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _buf["AssetName"]; }
        { var __json0 = _buf["BaseAttributes"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; BaseAttributes = new equipment.AttributeData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { equipment.AttributeData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = equipment.AttributeData.DeserializeAttributeData(__e0);  }  BaseAttributes[__index0++] = __v0; }   }
    }

    public static Equipment DeserializeEquipment(JSONNode _buf)
    {
        return new Equipment(_buf);
    }

    public readonly int Id;
    public readonly EquipmentType EquipmentType;
    public readonly equipment.QualityType Quality;
    public readonly string Name;
    public readonly string AssetName;
    public readonly equipment.AttributeData[] BaseAttributes;
   
    public const int __ID__ = -1214642834;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        foreach (var _e in BaseAttributes) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EquipmentType:" + EquipmentType + ","
        + "Quality:" + Quality + ","
        + "Name:" + Name + ","
        + "AssetName:" + AssetName + ","
        + "BaseAttributes:" + Luban.StringUtil.CollectionToString(BaseAttributes) + ","
        + "}";
    }
}

}
