
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EquipmentType
    {
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 0,
        /// <summary>
        /// 盔甲
        /// </summary>
        Armor = 1,
        /// <summary>
        /// 鞋子
        /// </summary>
        Boots = 2,
        /// <summary>
        /// 手套
        /// </summary>
        Glovers = 3,
    }

} 

