
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.equipment
{ 
    public enum QualityType
    {
        Common = 0,
        Magic = 1,
        Rare = 2,
        Legendary = 3,
        Unique = 4,
    }

} 

