
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Hero : Luban.BeanBase
{
    public Hero(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["EntityId"].IsNumber) { throw new SerializationException(); }  EntityId = _buf["EntityId"]; }
        EntityId_Ref = null;
        { if(!_buf["MaxHp"].IsNumber) { throw new SerializationException(); }  MaxHp = _buf["MaxHp"]; }
        { if(!_buf["MoveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["MoveSpeed"]; }
        { if(!_buf["AttackSpeed"].IsNumber) { throw new SerializationException(); }  AttackSpeed = _buf["AttackSpeed"]; }
        { if(!_buf["Attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["Attack"]; }
        { if(!_buf["Defense"].IsNumber) { throw new SerializationException(); }  Defense = _buf["Defense"]; }
    }

    public static Hero DeserializeHero(JSONNode _buf)
    {
        return new Hero(_buf);
    }

    public readonly int Id;
    public readonly int EntityId;
    public Entity EntityId_Ref;
    public readonly float MaxHp;
    public readonly float MoveSpeed;
    public readonly float AttackSpeed;
    public readonly float Attack;
    public readonly float Defense;
   
    public const int __ID__ = 2245658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        EntityId_Ref = tables.TbEntity.GetOrDefault(EntityId);
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "MaxHp:" + MaxHp + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "AttackSpeed:" + AttackSpeed + ","
        + "Attack:" + Attack + ","
        + "Defense:" + Defense + ","
        + "}";
    }
}

}
