
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ModifierData : Luban.BeanBase
{
    public ModifierData(JSONNode _buf) 
    {
        { if(!_buf["NumericType"].IsNumber) { throw new SerializationException(); }  NumericType = (NumericType)_buf["NumericType"].AsInt; }
        { if(!_buf["ModifierType"].IsNumber) { throw new SerializationException(); }  ModifierType = (ModifierType)_buf["ModifierType"].AsInt; }
        { if(!_buf["Value"].IsNumber) { throw new SerializationException(); }  Value = _buf["Value"]; }
    }

    public static ModifierData DeserializeModifierData(JSONNode _buf)
    {
        return new ModifierData(_buf);
    }

    public readonly NumericType NumericType;
    public readonly ModifierType ModifierType;
    public readonly float Value;
   
    public const int __ID__ = -448759999;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "ModifierType:" + ModifierType + ","
        + "Value:" + Value + ","
        + "}";
    }
}

}
