
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum NumericType
    {
        None = 0,
        Hp = 1,
        MaxHp = 2,
        MoveSpeed = 3,
        AttackSpeed = 4,
        Attack = 5,
        Defence = 6,
    }

} 

