
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbEntity TbEntity {get; }
    public TbEntityGroup TbEntityGroup {get; }
    public TbBullet TbBullet {get; }
    public TbHero TbHero {get; }
    public TbEffect TbEffect {get; }
    public TbUIForm TbUIForm {get; }
    public TbScene TbScene {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new TbItem(loader("Item"));
        TbEntity = new TbEntity(loader("Entity"));
        TbEntityGroup = new TbEntityGroup(loader("EntityGroup"));
        TbBullet = new TbBullet(loader("Bullet"));
        TbHero = new TbHero(loader("Hero"));
        TbEffect = new TbEffect(loader("Effect"));
        TbUIForm = new TbUIForm(loader("UIForm"));
        TbScene = new TbScene(loader("Scene"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbEntity.ResolveRef(this);
        TbEntityGroup.ResolveRef(this);
        TbBullet.ResolveRef(this);
        TbHero.ResolveRef(this);
        TbEffect.ResolveRef(this);
        TbUIForm.ResolveRef(this);
        TbScene.ResolveRef(this);
    }
}

}
