
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbEntityGroup
{
    private readonly System.Collections.Generic.Dictionary<int, EntityGroup> _dataMap;
    private readonly System.Collections.Generic.List<EntityGroup> _dataList;
    
    public TbEntityGroup(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EntityGroup>();
        _dataList = new System.Collections.Generic.List<EntityGroup>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EntityGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EntityGroup.DeserializeEntityGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EntityGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<EntityGroup> DataList => _dataList;

    public EntityGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EntityGroup Get(int key) => _dataMap[key];
    public EntityGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

